### ISSUE TITLE
Build issue 

### ISSUE THREAD

**Issue by thefiredragon** [dhruv22592/android_kernel_samsung_gts7xllite#1]
Dear you,
I have a question, which toolchain did u use to build this kernel source ?

I'm running by compiling into sub-make Error 2
This is happen after compiling Lot of Files.
I had try different toolchains,

Perhaps you could provide your build env settings and your steps to build 
Best Regards

**Comment by averyvisentin** [comment]
Darn, I swore this repo was private, it's not buildable yet. In the process of building TWRP for the tab S7. You can find a working dump on XDA under TAB S7 FE forum. Should be title "Experimental TWRP" or something of that nature. I'm sorry you wasted time with this.

**Comment by dhruv22592** [comment]
Hi, thank you for opening an issue, in the directory where you have the kernel, do:

```
mkdir -p toolchain/llvm-arm-toolchain-ship/
wget https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
tar -xf clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz -C toolchain/llvm-arm-toolchain-ship/
mv toolchain/llvm-arm-toolchain-ship/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/ toolchain/llvm-arm-toolchain-ship/10.0/
git clone -b android-9.0.0_r60  https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/ toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/
export CONFIG_SECTION_MISMATCH_WARN_ONLY=y
```

then install the **ncurses5** library. It must be ncurses5 otherwise it wont work, if you are using arch, you can install the ncurses5-compat-libs from the AUR and make sure that the default python executable is python2. 

(if you don't want to make python2 as default then you can edit the MakeFile and go to line 413 and replace $(PYTHON) with $(PYTHON2)).

after all that just re-run the build_kernel.sh script.

(if the build fails to run then try deleting the out/ directory and trying again)

**Comment by thefiredragon** [comment]
I had used Python2 runned into same issue. Also installed ncurses5 and -dev under ubuntu.

`  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/umac/scan/dispatcher/src/wlan_scan_utils_api.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/os_if/linux/scan/src/wlan_cfg80211_scan.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/os_if/linux/wlan_cfg80211.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/target_if/scan/src/target_if_scan.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/umac/cmn_services/utils/src/wlan_utility.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/spectral/core/spectral_offload.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/spectral/core/spectral_common.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/spectral/dispatcher/src/wlan_spectral_ucfg_api.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/spectral/dispatcher/src/wlan_spectral_utils_api.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/spectral/dispatcher/src/wlan_spectral_tgt_api.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/os_if/linux/spectral/src/wlan_cfg80211_spectral.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/os_if/linux/spectral/src/os_if_spectral_netlink.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/target_if/spectral/target_if_spectral_netlink.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/target_if/spectral/target_if_spectral_phyerr.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/target_if/spectral/target_if_spectral.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/target_if/spectral/target_if_spectral_sim.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/umac/green_ap/core/src/wlan_green_ap_main.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/umac/green_ap/dispatcher/src/wlan_green_ap_api.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/umac/green_ap/dispatcher/src/wlan_green_ap_ucfg_api.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/target_if/green_ap/src/target_if_green_ap.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/umac/cmn_services/crypto/src/wlan_crypto_global_api.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/umac/cmn_services/crypto/src/wlan_crypto_ucfg_api.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/umac/cmn_services/crypto/src/wlan_crypto_main.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/umac/cmn_services/crypto/src/wlan_crypto_obj_mgr.o
  CC      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/../qca-wifi-host-cmn/umac/cmn_services/crypto/src/wlan_crypto_param_handling.o
  AR      drivers/net/wireless/qualcomm/wcn39xx/qcacld-3.0/built-in.a
  AR      drivers/net/wireless/built-in.a
  AR      drivers/net/built-in.a
  AR      drivers/built-in.a
make[1]: Leaving directory '/mnt/cache/kernel/android_kernel-gts7xllite/out'
make: *** [Makefile:146: sub-make] Error 2
make: Leaving directory '/mnt/cache/kernel/android_kernel-gts7xllite'`

**Comment by thefiredragon** [comment]
Dear @dhruv22592 

I got own twrp build with your prebuilt Kernel working

https://github.com/thefiredragon/gts7xllite-twrp

This include multidisabler and works fine.

Till yet I dont got this Kernel builded own.

I have another question, did you modified your kernel ? Or is this Kernel in twrp untouched?

I would Like to know it because I'm trying to build twrp also for another device (r9q) but running in dm-verity issues after flashing for Galaxy s21 Fe.

Did you disabled dm-verity or Something in your Kernel?

**Comment by dhruv22592** [comment]
Hi, 

The kernel was able to compile properly with a clean install of Ubuntu 21.10, the things i did was:
- Install Ubuntu 21.10
- Reboot
- Run these commands: 
`sudo apt install make python-is-python2 libncurses5 gcc flex bison libssl-dev git`
`git clone https://github.com/dhruv22592/android_kernel_samsung_gts7xllite`
`cd android_kernel_samsung_gts7xllite`
`mkdir -p toolchain/llvm-arm-toolchain-ship/`
`wget https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz`
`tar -xf clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz -C toolchain/llvm-arm-toolchain-ship/`
`mv toolchain/llvm-arm-toolchain-ship/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/ toolchain/llvm-arm-toolchain-ship/10.0/`
`git clone -b android-9.0.0_r60  https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/ toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/`
`export CONFIG_SECTION_MISMATCH_WARN_ONLY=y`
`./build_kernel.sh`

After a while the kernel will complete compiling. Make sure it does not say error in any of the commands.

The kernel that I used in the twrp repository was extracted from **recovery.img** in the samsung firmware, so it's the stock kernel without any modifications done by me.

**Comment by thefiredragon** [comment]
Okay thank you, I'll create next days an overlay for phh gsi for this Tab. Also i Had rebuild your twrp Like Afaneh did.

Thank you for reply Here :)
